-- This Script is Part of the ZeroLua Obfuscator by Levno_710
--
-- config.lua
--
-- In this Script, some Global config Variables are defined

local NAME = "Zero Lua";
local REVISION = "Release";
local VERSION = "v5.2";
local BY = "Zero Team";

for _, currArg in pairs(arg) do
	if currArg == "--CI" then
		local releaseName = string.gsub(string.format("%s %s %s", NAME, REVISION, VERSION), "%s", "-")
		print(releaseName)
	end

	if currArg == "--FullVersion" then
		print(VERSION)
	end
end

-- Config Starts here
return {
	Name = NAME,
	NameUpper = string.upper(NAME),
	NameAndVersion = string.format("%s %s", NAME, VERSION),
	Version = VERSION;
	Revision = REVISION;
	-- Config Starts Here
	IdentPrefix = "__zero_"; -- The Prefix used for Identifiers generated by ZERO LUA.

	SPACE = " "; -- The Whitespace to be used by the unparser
	TAB = "\t"; -- The Tab Whitespace to be used by the unparser for pretty printing
}